# Composicao do programa do jogo de damas versao debug

[Diretorios]

Nome        =  JogoDeDamasDebug
PathDefault =  ..\Fontes
err         =  ..\Produto
obj			=  ..\Objetos
c			=  ..\Fontes
h			=  ..\Fontes

[Modulos]
Lista /D_DEBUG
Peca
Tabuleiro /D_DEBUG
TestTab /D_DEBUG
Jogo
Princip

[BuildInicio]
/OUT:..\Produto\JogoDeDamasDebug.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
