# Composicao do programa de teste da deturpação do tabuleiro

[Diretorios]

Nome        =  TesteTabuleiroDeturpa
PathDefault =  ..\Fontes
err         =  ..\Produto
obj			=  ..\Objetos
c			=  ..\Fontes
h			=  ..\Fontes

[Modulos]
Lista /D_DEBUG
Peca
Tabuleiro /D_DEBUG
TestTab /D_DEBUG

[BuildInicio]
/OUT:..\Produto\TesteTabuleiroDeturpa.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
